One-Hot Encoding:

Encoding

*converting catogarical data into numarical data
label and one-Hot 

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [5]:
df=pd.read_csv(r"C:\Users\DELL\Desktop\pythonfiles\Salary_EDA.csv")
df.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4   60000.0

In [11]:
categorical_cols=['Education Level']

defeine and apply encoder

In [12]:
encoder=OneHotEncoder(drop=None,sparse_output=False)

In [19]:
encoded_data=encoder.fit_transform(df[categorical_cols])

In [21]:
print (encoder_data)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


encode is in the form of array.now we need to convert the encoded features 

convert the encoded into dataframes with catagoris as coloumn names

In [39]:
encoded_df=pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out(categorical_cols))
encoded_df.head()

Education Level_Bachelor's  Education Level_Master's  Education Level_PhD  \
0                         1.0                       0.0                  0.0   
1                         0.0                       1.0                  0.0   
2                         0.0                       0.0                  1.0   
3                         1.0                       0.0                  0.0   
4                         1.0                       0.0                  0.0   

   Education Level_nan  
0                  0.0  
1                  0.0  
2                  0.0  
3                  0.0  
4                  0.0

In [40]:
encoded_df.drop(columns=['Education Level_nan'])

Education Level_Bachelor's  Education Level_Master's  Education Level_PhD
0                           1.0                       0.0                  0.0
1                           0.0                       1.0                  0.0
2                           0.0                       0.0                  1.0
3                           1.0                       0.0                  0.0
4                           1.0                       0.0                  0.0
..                          ...                       ...                  ...
370                         1.0                       0.0                  0.0
371                         0.0                       1.0                  0.0
372                         1.0                       0.0                  0.0
373                         1.0                       0.0                  0.0
374                         0.0                       0.0                  1.0

[375 rows x 3 columns]

In [41]:
encoded_df.drop(columns=['Education Level_nan'],axis=1)

Education Level_Bachelor's  Education Level_Master's  Education Level_PhD
0                           1.0                       0.0                  0.0
1                           0.0                       1.0                  0.0
2                           0.0                       0.0                  1.0
3                           1.0                       0.0                  0.0
4                           1.0                       0.0                  0.0
..                          ...                       ...                  ...
370                         1.0                       0.0                  0.0
371                         0.0                       1.0                  0.0
372                         1.0                       0.0                  0.0
373                         1.0                       0.0                  0.0
374                         0.0                       0.0                  1.0

[375 rows x 3 columns]

In [42]:
encoded_df.drop(columns=['Education Level_nan'],axis=0)

Education Level_Bachelor's  Education Level_Master's  Education Level_PhD
0                           1.0                       0.0                  0.0
1                           0.0                       1.0                  0.0
2                           0.0                       0.0                  1.0
3                           1.0                       0.0                  0.0
4                           1.0                       0.0                  0.0
..                          ...                       ...                  ...
370                         1.0                       0.0                  0.0
371                         0.0                       1.0                  0.0
372                         1.0                       0.0                  0.0
373                         1.0                       0.0                  0.0
374                         0.0                       0.0                  1.0

[375 rows x 3 columns]

In [47]:
final_df=pd.concat([df, encoded_df],axis=1)
final_df.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  Education Level_Bachelor's  Education Level_Master's  \
0   90000.0                         1.0                       0.0   
1   65000.0                         0.0                       1.0   
2  150000.0                         0.0                       0.0   
3   60000.0                         1.0                       0.0   
4   60000.0                         1.0                       0.0   

   Education Level_PhD  
0                  0.0  
1                  0.0  
2                  1.0  
3                  0.0  
4                  0.0

Label Encoding

In [48]:
from sklearn.preprocessing import LabelEncoder

In [50]:
df1=pd.read_csv(r"C:\Users\DELL\Desktop\pythonfiles\Salary_EDA.csv")
df1.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4   60000.0

In [52]:
le=LabelEncoder()
df1['Gender_encoded']=le.fit_transform(df['Gender'])
df1.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  Gender_encoded  
0   90000.0               1  
1   65000.0               0  
2  150000.0               1  
3   60000.0               0  
4   60000.0               0

In [53]:
le1=LabelEncoder()
df1['phd']=le1.fit_transform(df['Gender'])
df1.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  Gender_encoded  phd  
0   90000.0               1    1  
1   65000.0               0    0  
2  150000.0               1    1  
3   60000.0               0    0  
4   60000.0               0    0

In [54]:
from sklearn.preprocessing import MinMaxScaler

In [56]:
df2=pd.read_csv(r"C:\Users\DELL\Desktop\pythonfiles\Salary_EDA.csv")
df2.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4   60000.0

In [57]:
Scaler=MinMaxScaler()
df2[['Salary_Scaled']]=Scaler.fit_transform(df2[['Salary']])
df2[['Salary','Salary_Scaled']]
df2.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  Salary_Scaled  
0   90000.0       0.359103  
1   65000.0       0.258963  
2  150000.0       0.599439  
3   60000.0       0.238935  
4   60000.0       0.238935

In [58]:
from sklearn.preprocessing import StandardScaler

In [60]:
df3=pd.read_csv(r"C:\Users\DELL\Desktop\pythonfiles\Salary_EDA.csv")
df3.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4   60000.0

In [61]:
Scaler=StandardScaler()
df2[['Standard_Scaled']]=Scaler.fit_transform(df2[['Salary']])
df2[['Salary','Standard_Scaled']]
df2.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  36.0  Female      Bachelor's    Sales Associate                  7.0   

     Salary  Salary_Scaled  Standard_Scaled  
0   90000.0       0.359103        -0.211488  
1   65000.0       0.258963        -0.733148  
2  150000.0       0.599439         1.040496  
3   60000.0       0.238935        -0.837480  
4   60000.0       0.238935        -0.837480